### ISSUE TITLE
Purpose of importing modules in /src/application/lib/email-lib.xqy

### ISSUE THREAD

**Issue by jeet1212** [garyvidal/xquerrail#10]
Hi Gary,

I just wanted to know, why are you importing following models in the /src/application/lib/email-lib.xqy as these files don't exist inside the model directory and also you are not using them in the framework. is any future plan of using these?

if somebody would want to use email-lib, the error will be shown 'In /application/lib/email-lib.xqy on line 8
In xdmp:eval("xquery version &quot;1.0-ml&quot;;&#10; import module namespace ...", (), <options xmlns="xdmp:eval"><database>5673965288987607519</database......"' 

import module namespace jm = "http://www.xquerrail-framework.com/model/job"
    at "/application/model/job-model.xqy";
import module namespace pm = "http://www.xquerrail-framework.com/model/project"
    at "/application/model/project-model.xqy";
import module namespace vm = "http://www.xquerrail-framework.com/model/vendor"
    at "/application/model/vendor-model.xqy";
import module namespace um = "http://www.xquerrail-framework.com/model/user"
    at "/application/model/user-model.xqy";

Thanks & Regards,
Indy

**Comment by garyvidal** [comment]
That is dead code and should have been removed.  You may need to clean your repository to remove these infelicities
