### ISSUE TITLE
Route is incorrect for default login

### ISSUE THREAD

**Issue by jeet1212** [garyvidal/xquerrail#2]
Currently it is,

 <route id="_default" pattern="^/$">
      <default key="_controller">application:default:index:html</default>
   </route>

It should be,

 <route id="_default" pattern="^/$">
      <default key="_controller">application:default:login:html</default>
   </route>

**Comment by garyvidal** [comment]
Login redirection is handled through interception framework.  Login page is never to be used unless using ml-security interceptor and scope context.  I will review and fix shortly.

**Comment by jeet1212** [comment]
it is fine now. that problem was only coming due to invalid user selection in the app as a default user. anonymous user needs to be selected.
