### ISSUE TITLE
Anonymous user needs previlege

### ISSUE THREAD

**Issue by srinivasan1987** [garyvidal/xquerrail#7]
Hi gary,

For my marklogic app server am not using admin user. I am using one anonymous user who has all required role. When ever i chosse that user as default user in app server i cant run framework it gives the following error..

Application Error!
Code:   SEC-PRIV
Name:  
XQuery Version: 1.0-ml
Message:    Need privilege
Formatted:  SEC-PRIV: xdmp:security-assert("http://marklogic.com/xdmp/privileges/get-role-names", "execute") -- Need privilege: http://marklogic.com/xdmp/privileges/get-role-names
Retryable:  false
Expression: xdmp:security-assert("http://marklogic.com/xdmp/privileges/get-role-names", "execute")

**Comment by garyvidal** [comment]
The following link includes the correct permissions for role/user configuration

https://github.com/garyvidal/xquerrail/wiki/Server-Configuration---Anonymous-Role-User-Configuration

In future system will bootstrap server with all configurations necessary for application.
